base_url = "https://m1sk9.dev"
title = "m1sk9 | Sho Sakuma"
description = "m1sk9's portfolio and blog about programming."
default_language = "en"
theme = "serene"
output_dir = "build"
compile_sass = true
minify_html = false
build_search_index = false
generate_feeds = false
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = "Sho Sakuma"
id = "m1sk9"
bio = "Only what I want to do."
avatar = "/media/avatar.jpg"

display_id = false
display_bio = false
display_avatar = false

links = [
  { name = "GitHub", icon = "github", url = "https://github.com/m1sk9/m1sk9.dev" },
]

recent = true
recent_max = 5
recent_more_text = "more »"

sections = [
  { name = "Posts", path = "/posts", is_external = false },
  { name = "Tags", path = "/tags", is_external = false },
  { name = "GitHub", path = "https://github.com/m1sk9/m1sk9.dev", is_external = true },
]
blog_section_path = "/posts"

force_theme = false
blog_categorized = false
blur_effect = false
back_to_top = true
toc = true
copy = true
comment = false
display_tags = true
truncate_summary = true

reaction = false
reaction_align = "right"
reaction_endpoint = ""

outdate_alert = true
outdate_alert_days = 120
outdate_alert_text_before = ""
outdate_alert_text_after = " days ago and may be out of date."

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

footer_copyright = "© 2024-2025 m1sk9"
footer_credits = true

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"

back_link_text = "Back"
